model-settings:
  prediction-threshold: 0.23  # max value of cosine similarity can be 1
  model-name: 'ViT-B/32'
  device: 'cpu'
label-settings:
  labels: # labels that can be predicted if model's confidence is more than "prediction-threshold"
    # outdoor cases
    # - 'people walking on a street'
    # - 'buildings'
    - 'Violence'
    # - 'fire on a street'
    # - 'street violence'
    # - 'road'
    # - 'car crash'
    # - 'cars on a road'
    # - 'car parking area'
    # - 'cars'
    # indoor cases
    # - 'office environment'
    # - 'office corridor'
    # - 'violence in office'
    # - 'fire in office'
    # - 'people talking'
    # - 'people walking in office'
    # - 'person walking in office'
    # - 'group of people'
    - 'Violence'
  default-label: 'Non-Violence' # value to return if model's confidence is less than "prediction-threshold"

